# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 07:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateField(blank=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Wrk', 'Work'), ('Ed', 'Education'), ('Hob', 'Hobby'), ('Vol', 'Volunteer')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceToSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badicv.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badicv.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillToType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badicv.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('type', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='skilltotype',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badicv.SkillType'),
        ),
        migrations.AddField(
            model_name='experiencetoskill',
            name='skill_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badicv.Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltotype',
            unique_together=set([('skill_name', 'skill_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='experiencetoskill',
            unique_together=set([('experience_name', 'skill_name')]),
        ),
    ]
