# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badicv', '0004_auto_20171019_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
