# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 21:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badicv', '0005_auto_20171020_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referees',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='referees',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{0,2} ?\\d? ?\\d{3} ?\\d{4}$')]),
        ),
    ]
