# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 21:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badicv', '0006_auto_20171021_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999' or '+99 9 999 9999'", regex='^\\+?\\d{0,2} ?\\d? ?\\d{3} ?\\d{4}$')])),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badicv.Experience')),
            ],
        ),
        migrations.RemoveField(
            model_name='referees',
            name='experience',
        ),
        migrations.DeleteModel(
            name='Referees',
        ),
    ]
