# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badicv', '0007_auto_20171021_1016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skilltotype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='skilltotype',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='skilltotype',
            name='skill_type',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(through='badicv.ExperienceWithSkill', to='badicv.Skill'),
        ),
        migrations.AddField(
            model_name='referee',
            name='experiences',
            field=models.ManyToManyField(to='badicv.Experience'),
        ),
        migrations.AddField(
            model_name='skill',
            name='types',
            field=models.ManyToManyField(to='badicv.SkillType'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='experiencewithskill',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='SkillToType',
        ),
    ]
