# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 03:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badicv', '0008_auto_20171021_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999' or '+99 9 999 9999'", regex='^\\+?\\d{0,2} ?\\d? ?\\d{3} ?\\d{4}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='referee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phone',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badicv.Referee'),
        ),
        migrations.AddField(
            model_name='email',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badicv.Referee'),
        ),
    ]
