# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badicv', '0009_auto_20171025_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencewithskill',
            old_name='experience_name',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='experiencewithskill',
            old_name='skill_name',
            new_name='skill',
        ),
        migrations.AlterUniqueTogether(
            name='experiencewithskill',
            unique_together=set([('experience', 'skill')]),
        ),
    ]
